FROM krallin/ubuntu-tini:16.04
LABEL maintainer.1.name="Alexander Scholz" \
      maintainer.1.email="alexander.scholz@izi.fraunhofer.de" \
      maintainer.2.name="Christoph Kämpf" \
      maintainer.2.email="christoph.kaempf@izi.fraunhofer.de"

#############################
# Software Versions Section #
#############################

#################################
# Software Installation Section #
#################################
RUN apt-get update && apt-get install -y \
    bash-completion \
    bzip2 \
    curl \
    emacs \
    git \
    graphviz \
    g++ \
    libncurses5-dev \
    libz-dev \
    make \
    man \
    pigz \
    python-dev \
    python-pip \
    python-virtualenv \
    sed \
    unzip \
    vim \
    wget \
    zlib1g-dev

###############################################################################
# Install Broad Institute's picard
###############################################################################

RUN apt-get install -y \
    picard-tools


# Clean up APT when done.
USER root
RUN apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

# Create user 'uap_user'
RUN useradd -ms /bin/bash uap_user
USER uap_user

###############################################################################
# Install required bioinformatic tools
###############################################################################

# Create required directories

RUN mkdir -p \
    /home/uap_user/bioinformatic-tools

###############################################################################
# Install bowtie2 (version: 2.2.9)
###############################################################################

RUN mkdir -p /home/uap_user/bioinformatic-tools/bowtie2
WORKDIR /home/uap_user/bioinformatic-tools/bowtie2
RUN wget https://github.com/BenLangmead/bowtie2/releases/download/v2.2.9/bowtie2-2.2.9-source.zip && \
    unzip bowtie2-2.2.9-source.zip && \
    rm bowtie2-2.2.9-source.zip && \
    cd /home/uap_user/bioinformatic-tools/bowtie2/bowtie2-2.2.9 && \
    make
ENV PATH /home/uap_user/bioinformatic-tools/bowtie2/bowtie2-2.2.9:$PATH

###############################################################################
# Install bwa (version: 0.7.15)
###############################################################################

RUN mkdir -p /home/uap_user/bioinformatic-tools/bwa
WORKDIR /home/uap_user/bioinformatic-tools/bwa
RUN wget https://github.com/lh3/bwa/releases/download/v0.7.15/bwa-0.7.15.tar.bz2 && \
    tar -xjf bwa-0.7.15.tar.bz2 && \
    rm bwa-0.7.15.tar.bz2
WORKDIR /home/uap_user/bioinformatic-tools/bwa/bwa-0.7.15
RUN make
ENV PATH /home/uap_user/bioinformatic-tools/bwa/bwa-0.7.15:$PATH


###############################################################################
# Install cufflinks (version 2.2.1)
###############################################################################

RUN mkdir -p /home/uap_user/bioinformatic-tools/cufflinks
WORKDIR /home/uap_user/bioinformatic-tools/cufflinks
RUN wget http://cole-trapnell-lab.github.io/cufflinks/assets/downloads/cufflinks-2.2.1.Linux_x86_64.tar.gz && \
    tar -xzvf cufflinks-2.2.1.Linux_x86_64.tar.gz && \
    rm cufflinks-2.2.1.Linux_x86_64.tar.gz
ENV PATH /home/uap_user/bioinformatic-tools/cufflinks/cufflinks-2.2.1.Linux_x86_64:$PATH

###############################################################################
# Install cutadapt
###############################################################################

RUN pip install --user --upgrade cutadapt

###############################################################################
# Install FastQC (version: 0.11.7)
###############################################################################

RUN mkdir -p /home/uap_user/bioinformatic-tools/fastqc
WORKDIR /home/uap_user/bioinformatic-tools/fastqc
RUN wget http://www.bioinformatics.babraham.ac.uk/projects/fastqc/fastqc_v0.11.7.zip && \
    unzip fastqc_v0.11.7.zip && \
    chmod u+x FastQC/fastqc
ENV PATH /home/uap_user/bioinformatic-tools/fastqc/FastQC:$PATH

###############################################################################
# Install Fastx-Toolkit (version: 0.0.13)
###############################################################################

RUN mkdir -p /home/uap_user/bioinformatic-tools/fastx-toolkit
WORKDIR /home/uap_user/bioinformatic-tools/fastx-toolkit
RUN wget http://hannonlab.cshl.edu/fastx_toolkit/fastx_toolkit_0.0.13_binaries_Linux_2.6_amd64.tar.bz2 && \
    tar -xjvf fastx_toolkit_0.0.13_binaries_Linux_2.6_amd64.tar.bz2 && \
    rm fastx_toolkit_0.0.13_binaries_Linux_2.6_amd64.tar.bz2
ENV PATH /home/uap_user/bioinformatic-tools/fastx-toolkit/bin:$PATH

###############################################################################
# Install fetchChromSizes
###############################################################################

RUN mkdir -p /home/uap_user/bioinformatic-tools/fetchChromSizes
WORKDIR /home/uap_user/bioinformatic-tools/fetchChromSizes
RUN wget https://raw.githubusercontent.com/ucscGenomeBrowser/kent/master/src/utils/userApps/fetchChromSizes && \
    chmod u+x fetchChromSizes
ENV PATH /home/uap_user/bioinformatic-tools/fetchChromSizes:$PATH

###############################################################################
# Install HTSeq
###############################################################################

RUN pip install --user --upgrade HTSeq

###############################################################################
# Install MACS2
###############################################################################

RUN pip install --user --upgrade MACS2

###############################################################################
# Install samtools (version: 1.3.1)
###############################################################################

RUN mkdir -p /home/uap_user/bioinformatic-tools/samtools
WORKDIR /home/uap_user/bioinformatic-tools/samtools
RUN wget https://github.com/samtools/samtools/releases/download/1.3.1/samtools-1.3.1.tar.bz2 && \
    tar -xjf samtools-1.3.1.tar.bz2 && \
    rm samtools-1.3.1.tar.bz2
WORKDIR /home/uap_user/bioinformatic-tools/samtools/samtools-1.3.1
RUN ./configure && \
    make

# switch to root-user for install
USER root
RUN make install

USER uap_user
ENV PATH /home/uap_user/bioinformatic-tools/samtools/samtools-1.3.1:$PATH

###############################################################################
# Install segemehl (version: 0.2.0)
###############################################################################

RUN mkdir -p /home/uap_user/bioinformatic-tools/segemehl
WORKDIR /home/uap_user/bioinformatic-tools/segemehl
RUN wget http://www.bioinf.uni-leipzig.de/Software/segemehl/old/segemehl_0_2_0.tar.gz && \
    tar -xzf segemehl_0_2_0.tar.gz && \
    rm segemehl_0_2_0.tar.gz
WORKDIR /home/uap_user/bioinformatic-tools/segemehl/segemehl_0_2_0/segemehl
RUN make
ENV PATH /home/uap_user/bioinformatic-tools/segemehl/segemehl_0_2_0/segemehl:$PATH

###############################################################################
# Install tophat2 (version: 2.1.1)
###############################################################################

RUN mkdir -p /home/uap_user/bioinformatic-tools/tophat2
WORKDIR /home/uap_user/bioinformatic-tools/tophat2
RUN wget http://ccb.jhu.edu/software/tophat/downloads/tophat-2.1.1.Linux_x86_64.tar.gz && \
    tar -xzf tophat-2.1.1.Linux_x86_64.tar.gz && \
    rm tophat-2.1.1.Linux_x86_64.tar.gz
ENV PATH /home/uap_user/bioinformatic-tools/tophat2/tophat-2.1.1.Linux_x86_64:$PATH


###############################################################################
# Install uap
###############################################################################

RUN mkdir -p /home/uap_user/uap
WORKDIR /home/uap_user/uap
RUN git clone https://github.com/yigbt/uap.git . && \
    git checkout release && \
    ./bootstrap.sh
ENV PATH /home/uap_user/uap:$PATH


###############################################################################
# Run uap workflows
###############################################################################

WORKDIR /home/uap_user/uap/example-configurations/

# Run workflow 'index_mycoplasma_genitalium_ASM2732v1_genome.yaml'
RUN mkdir -p /home/uap_user/uap/example-configurations/genomes/bacteria/Mycoplasma_genitalium && \
    uap index_mycoplasma_genitalium_ASM2732v1_genome.yaml run-locally

# Run workflow 'index_homo_sapiens_hg19_chr21.yaml'
RUN mkdir -p \
    /home/uap_user/uap/example-configurations/genomes/animalia/chordata/mammalia/primates/homo_sapiens/hg19/chromosome_sizes \
    /home/uap_user/uap/example-configurations/genomes/animalia/chordata/mammalia/primates/homo_sapiens/hg19/fasta && \
    uap index_homo_sapiens_hg19_chr21.yaml run-locally

RUN mkdir -p \
    /home/uap_user/uap/example-configurations/genomes/animalia/chordata/mammalia/primates/homo_sapiens/gencode \
    /home/uap_user/uap/example-configurations/example-out/2014-Mercer_et_al_download

###############################################################################
# Prepare bash prompt, README and welcome banner
###############################################################################

# switch to user and directory
WORKDIR /home/uap_user
# Enable git shell completion and advanced styling
RUN git clone https://github.com/magicmonty/bash-git-prompt.git .bash-git-prompt --depth=1
COPY docker-uap.bashrc /home/uap_user/.bashrc
COPY docker-uap.README.md /home/uap_user/README
COPY docker-uap.welcome_banner /home/uap_user/.welcome_banner

# Enable GIT_PROMPT_START
RUN sed -i "s/# GIT_PROMPT_START=.../GIT_PROMPT_START=\"uap Docker container (_LAST_COMMAND_INDICATOR_)\\\n\\\w\"/" /home/uap_user/.bashrc

# Add pip's local installation directory to PATH
ENV PATH /home/uap_user/.local/bin:$PATH

# Use baseimage-docker's init system.
ENTRYPOINT ["/usr/local/bin/tini", "--", "/bin/bash"]
