FROM kmpf/uap:1.0.0
LABEL maintainer.1.name="Alexander Scholz" \
      maintainer.1.email="alexander.scholz@izi.fraunhofer.de" \
      maintainer.2.name="Christoph Kämpf" \
      maintainer.2.email="christoph.kaempf@izi.fraunhofer.de"

###############################################################################
# Update uap repo
###############################################################################

WORKDIR /home/uap_user/uap/
RUN git pull origin master

###############################################################################
# Run uap workflows
###############################################################################

WORKDIR /home/uap_user/uap/example-configurations/

# Run workflow 'ChIPseq-data-download-short.yaml'
RUN mkdir -p /home/uap_user/uap/example-configurations/example-out/2007-Barski_et_al_download && \
    uap ChIPseq-data-download-short.yaml run-locally

# Create directories necessary for 'ChIPseq-workflow-short.yaml'
RUN mkdir -p \
    /home/uap_user/uap/example-configurations/example-out/2007-Barski_et_al

# Use baseimage-docker's init system.
WORKDIR /home/uap_user/
ENTRYPOINT ["/usr/local/bin/tini", "--", "/bin/bash"]
